"""
Django settings for portal_pj project.

Generated by 'django-admin startproject' using Django 2.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
# apps配下にフォルダをアプリフォルダを配置できるようにする
import sys

# 多言語化の絞り込み
from django.utils.translation import ugettext_lazy as _

# メッセージのclassを定義する(サーバサイドからフロントへのメッセージ)
from django.contrib.messages import constants as message_constants

# 時刻取得
from datetime import datetime, timedelta


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'boctx=r@z-3q7l2li@+oz9k_czzskli37c0$&tz^e$ehi3n$de'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

# ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'webpack_loader',
    'bootstrap4',
    'betterforms',
    'widget_tweaks',
    'django.forms', #Formでチェックボックスをカスタムする際に必要
    'contracts',
    'django.contrib.humanize',
    'bulk',
    'payment',
    'bootstrap_datepicker_plus',
    'chartjs',



]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_session_timeout.middleware.SessionTimeoutMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    # },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

#LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'ja'

#TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

# STATIC_URL = '/static/'

# アプリケーションディレクトリをプロジェクト直下のappsフォルダにまとめる
sys.path.append(os.path.join(BASE_DIR, 'apps'))
sys.path.insert(0,BASE_DIR)

# # Gメールで送信する例
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'ryookinawa@gmail.com' # Gmailのアカウント*
EMAIL_HOST_PASSWORD = 'jqwmookzxurideve' # Gmailの2段階認証用のパスワード*
EMAIL_USE_TLS = True
EMAIL_FROM_ADDRESS = 'admin@hoge.com'

#EMAIL_HOST_USER-CONTACT = 'koharu.y.1120@gmail.com' # Gmailのアカウント*

# ログイン画面
LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'accounts:home'
LOGOUT_REDIRECT_URL = 'accounts:login'

# 認証先テーブル
AUTH_USER_MODEL = 'accounts.User'

# add
# JWT_AUTH = {
#     'JWT_EXPIRATION_DELTA': timedelta(minutes=60),
#     'JWT_GET_USER_SECRET_KEY': 'users.models.jwt_get_secret_key',
# }

# payjp
# PAYJP_PUBLICKEY = "pk_test_06bb7e9f148cb89ad3207b57"
# PAYJP_SECRETKEY = "sk_test_311b85d9de92611e5541eef4"

# Stripe
STRIPE_PUBLISHABLE_KEY = "pk_test_51LedKvI8iZ48PSn6609eP61rSHlBUx2Vyna8tGZJ6CypIO5YWRCYgFD9XuxQtOJsJF170yZh92hCTE1Dp1b15JUh00Y61NzMPI"
STRIPE_API_KEY = "sk_test_51LedKvI8iZ48PSn6Yk3ahv35v7CaRdGZGgmFAkb3X3PWjwhK37qzvOJFSXPAuvCD7o87lixLapAGmW5PkNJMFMkl00qnVQeTbb"
STRIPE_WEBHOOK_SECRET = 'ここにSTRIPE_WEBHOOK_SECRETを入力（現時点でここはまだ修正しなくてOKです）'

# # 見積
TAX = 0.10
NUMBER_GROUPING = 3 #3桁でカンマを入れる

# # 翻訳ファイルの場所
# LOCALE_PATHS = (
#     os.path.join(BASE_DIR, 'locale'),
# )

# # 一括操作
# # エクスポートヘッダー
EXPORT_HEADER_JP = ["メールアドレス(必須)", "姓(必須)", "名(必須)", "ミドルネーム", "ふりがな(姓)", "ふりがな(名)", "ふりがな(ミドルネーム)", "利用サービス", "説明"]
#EXPORT_HEADER_JP = ["*1.mailaddress", "*2.lastname", "*3.firstname", "4.middlename", "5.lastname(kana)", "6.firstname(kana)", "7.middlename(kana)", "8.service", "9.memo"]
# EXPORT_HEADER_EN = ["Mail Address(Must)", "Last Name(Must)", "First Name(Must)", "Middle Name", "Last Name(Kana)", First Name(Kana), "Services", "Description"]

# # 多言語化メニューの絞り込み
# LANGUAGES = [
#     ('en', _('English')),
#     ('ja', _('Japanese')),
# ]

# 自動ログアウト(クッキーのタイムアウトを設定)
SESSION_COOKIE_AGE = 7200 #秒
# 操作しない場合にタイムアウトになる時間
SESSION_EXPIRE_SECONDS = 7200 #秒
# 最後のアクティビティーからSESSION_EXPIRE_SECONDS後にタイムアウトする
SESSION_EXPIRE_AFTER_LAST_ACTIVITY = True

# メッセージをサーバサイドからフロントへ送信する際の保存先？
MESSAGE_STORAGE = 'django.contrib.messages.storage.cookie.CookieStorage'
MESSAGE_TAGS = {
    message_constants.SUCCESS: 'alert alert-success',
    message_constants.ERROR: 'alert alert-danger',
}

# FORMでチェックボックスをカスタマイズする場合に追加
FORM_RENDERER = 'django.forms.renderers.TemplatesSetting'

# WebPackを読むための設定
WEBPACK_LOADER = {
    'DEFAULT': {
        'BUNDLE_DIR_NAME': '',
        'STATS_FILE': os.path.join(BASE_DIR, 'webpack-stats.json'),
    }
}

# # pk と modelがない形でquerysetをJSONに変換するシリアライザ（カスタム）
# SERIALIZATION_MODULES = {
#     "plainjson": "config.serializers"
# }
